name: Deploy Cloud Function

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_APPLICATION_CREDENTIALS }}

      - name: Deploy Cloud Function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: 'com.knoldus.cloudfunction.PubSubDataHandler'   # Replace with your Google Cloud Function name
          runtime: 'java17'   # Replace with the appropriate runtime
          event_trigger_type: ${{ secrets.EVENT_TRIGGER_TYPE }}
          event_trigger_resource: ${{ secrets.EVENT_TRIGGER_RESOURCE }}

      # Example of using the output
      - name: Test the deployed function
        run: curl "${{ steps.deploy.outputs.url }}"
