name: Deploy Cloud Function

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Image
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: |
          
          docker login --username $username --password $password ghcr.io
          docker build . --tag ghcr.io/sahilbabbar12/googlecloudfunction:latest
          docker push ghcr.io/sahilbabbar12/googlecloudfunction:latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          service_account_key: ${{ secrets.GCLOUD_APPLICATION_CREDENTIALS }}

      - name: Deploy Cloud Function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: 'vehicle-function'   # Replace with your Google Cloud Function name
          runtime: 'java17'   # Replace with the appropriate runtime

      # Example of using the output
      - name: Test the deployed function
        run: curl "${{ steps.deploy.outputs.url }}"
